export interface IFlight {
    time: string,
    destination: string,
    number: string,
    arrivalTime: string,
    status: boolean,
    delay: boolean
}

export const data: Array<IFlight> = [
    {
        "number" : "1",
        "destination" : "Лондон",
        "time" : "17:00",
        "arrivalTime" : "21:00",
        "status" : true,
        "delay" : false,
    },
    {
        "number" : "1",
        "destination" : "Лондон",
        "time" : "17:00",
        "arrivalTime" : "21:00",
        "status" : true,
        "delay" : false,
    },
    {
        "number" : "1",
        "destination" : "Лондон",
        "time" : "17:00",
        "arrivalTime" : "21:00",
        "status" : true,
        "delay" : false,
    },
    {
        "number" : "1",
        "destination" : "Лондон",
        "time" : "17:00",
        "arrivalTime" : "21:00",
        "status" : true,
        "delay" : false,
    },
    {
        "number" : "1",
        "destination" : "Лондон",
        "time" : "17:00",
        "arrivalTime" : "21:00",
        "status" : true,
        "delay" : false,
    },
    {
        "number" : "16",
        "destination" : "Лондон",
        "time" : "17:00",
        "arrivalTime" : "21:00",
        "status" : false,
        "delay" : true,
    },
    {
        "number" : "14",
        "destination" : "Лондон",
        "time" : "17:00",
        "arrivalTime" : "21:00",
        "status" : true,
        "delay" : false,
    },
    {
        "number" : "123",
        "destination" : "Лондон",
        "time" : "17:00",
        "arrivalTime" : "21:00",
        "status" : true,
        "delay" : true,
    },
    {
        "number" : "12",
        "destination" : "Лондон",
        "time" : "17:00",
        "arrivalTime" : "21:00",
        "status" : false,
        "delay" : false,
    },
    {
        "number" : "111",
        "destination" : "Лондон",
        "time" : "17:00",
        "arrivalTime" : "21:00",
        "status" : true,
        "delay" : false,
    },
    {
        "number" : "121",
        "destination" : "Лондон",
        "time" : "17:00",
        "arrivalTime" : "21:00",
        "status" : true,
        "delay" : false,
    },
    {
        "number" : "131",
        "destination" : "Лондон",
        "time" : "17:00",
        "arrivalTime" : "21:00",
        "status" : true,
        "delay" : false,
    },
    {
        "number" : "141",
        "destination" : "Лондон",
        "time" : "17:00",
        "arrivalTime" : "21:00",
        "status" : true,
        "delay" : true,
    }    
];
